In [10]:

import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

from scipy.io import loadmat
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split


In [16]:

# df = pd.read_csv( "mnist_train.csv" )
mnist = pd.read_csv( "mnist_train.csv" )
mnist_data = mnist.iloc[:,1:]
mnist_label = mnist.iloc[:, 0]


In [19]:
print(mnist_label.shape)
print(mnist_data.shape)

(60000,)
(60000, 784)


In [21]:
mnist_datac=mnist_data.to_numpy()

In [22]:
print(mnist_datac)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
data= mnist_datac
mean = np.mean(data, axis=1, keepdims=True)
std = np.std(data, axis=1, keepdims=True)
data_normalized = (data - mean)/std
print(data_normalized.shape)


(60000, 784)


In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(data_normalized, mnist_label, test_size=0.20, random_state=42)
Y_train = Y_train.values.reshape(Y_train.shape[0],1)
Y_test = Y_test.values.reshape(Y_test.shape[0],1)

In [28]:
print(X_test.shape)
print(X_train.shape)
print(Y_test.shape)
print(Y_train.shape)

(12000, 784)
(48000, 784)
(12000, 1)
(48000, 1)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv( "mnist_train.csv"  )
print(df.shape)
feature = df.iloc[:,1:].values #X
target = df.iloc[:, 0].values  #Y

# mnist = pd.read_csv( "mnist_train.csv" )
# mnist_data = mnist.iloc[:,1:]
# mnist_label = mnist.iloc[:, 0]


X_train, X_test, y_train,  y_test = train_test_split(feature, target, train_size=0.8, random_state = 6)
# X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5, random_state = 4)

learning_rate = 0.0001
iterations = 300
      
#fit
row_m , coloumn_n = X_train.shape
w= np.zeros(coloumn_n)
b=0

for i in range( iterations ) :
    A = 1 / ( 1 + np.exp( - ( X_train.dot( w ) + b ) ) )
    temp = ( A - y_train.T )   #Y_train.T       
    temp = np.reshape( temp, row_m )        
    dW = np.dot( X_train.T, temp ) / row_m         
    db = np.sum( temp ) / row_m 
          
        # update weights    
    w = w - learning_rate * dW    
    b = b - learning_rate * db

#predict
Z = 1 / ( 1 + np.exp( - ( X_test.dot( w ) + b ) ) )        
Y_p = np.where( Z > 0.5, 1, 0 )

correct_decided=0

counters=0
for counter in range( np.size( Y_p ) ) :  
        
        if y_test[counter] == Y_p[counter] :    #Y_train.T        
            correct_decided = correct_decided + 1
              
        counters = counters + 1

print( "Accuracy on test set by our model       :  ", ( correct_decided / counters ) * 100 )